strings:
  inputs: 
    - EasyMusic/en.lproj/Localizable.strings
  outputs:
    - templateName: structured-swift4
      output: Generated/strings.swift
xcassets:
  inputs:
    - EasyMusic/Assets.xcassets
    #- GraffitiBackgrounds/Colors.xcassets
  outputs:
    - templateName: swift4
      output: Generated/assets.swift
