language: swift
jobs:
    include:
        - script: xcodebuild -project TestExtensions.xcodeproj -scheme TestExtensionsTests-macOS -destination platform\=OS\ X,arch\=x86_64 test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED=NO TRAVIS=1 | xcpretty && exit ${PIPESTATUS[0]}
        - script: xcodebuild -project TestExtensions.xcodeproj -scheme TestExtensionsTests-iOS -destination platform\=iOS\ Simulator,name=iPhone\ 6 test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED=NO TRAVIS=1 | xcpretty && exit ${PIPESTATUS[0]}
        - script: xcodebuild -project TestExtensions.xcodeproj -scheme TestExtensionsTests-tvOS -destination platform\=tvOS\ Simulator,name=Apple\ TV test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED=NO TRAVIS=1 | xcpretty && exit ${PIPESTATUS[0]}
osx_image: xcode10
